name = "gakusei-chiebukuro-frontend"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-11-09"
compatibility_flags = ["nodejs_compat"]


[vars]
NEXT_PUBLIC_API_BASE_URL = "https://gakusei-chiebukuro-api.fuyu28.workers.dev"

[env.preview.vars]
NEXT_PUBLIC_API_BASE_URL = "https://gakusei-chiebukuro-api.fuyu28.workers.dev"
